services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: padreperdonalos
      MYSQL_DATABASE: cofradiario
    volumes:
      - dbdata:/var/lib/mysql # Persistencia de datos
    networks:
      - app_network

  backend:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on: 
      - db
    env_file:
      - ./backend/backend/.env
    volumes:
      - ./backend/backend:/var/www/html
    networks:
      - app_network
    command: sh -c "while true; do php artisan schedule:run --verbose; sleep 60; done & apache2-foreground"
    

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  dbdata:


networks:
  app_network:
    driver: bridge
